### ISSUE TITLE
Two radiography core UI tests seem to be broken on API 30

### ISSUE THREAD

**Issue by zach-klippenstein** [square/radiography#130]
These are failing on main, as well as on the last two PRs. Doesn't seem to be related to a code change.

```
radiography.test.RadiographyUiTest > when_showDialog_then_hierarchyHasTwoWindows[test(AVD) - 11] FAILED 
	expected to be true
	at radiography.test.RadiographyUiTest.waitForFocus(RadiographyUiTest.kt:142)

radiography.test.RadiographyUiTest > when_onlyFocusedWindow_then_hierarchyHasOnlyDialog[test(AVD) - 11] FAILED 
	expected to be true
	at radiography.test.RadiographyUiTest.waitForFocus(RadiographyUiTest.kt:142)

```

**Comment by zach-klippenstein** [comment]
Trying to repro locally, so far no success.

**Comment by zach-klippenstein** [comment]
Hm, this looks suspicious, from one of the CI logs:
```
Your emulator is out of date, please update by launching Android Studio:
 - Start Android Studio
 - Select menu "Tools > Android > SDK Manager"
 - Click "SDK Tools" tab
 - Check "Android Emulator" checkbox
 - Click "OK"
```

**Comment by zach-klippenstein** [comment]
I have spent some time trying to figure this out, which is twice the amount of time I had planned to spend on this today, and am stumped. The failing tests pass very reliably locally on a 30 emulator (ran in a loop for a few minutes, never failed). The tests all pass quite reliably on all the other emulators. The 30 emulator image has given me problems in other repos as well. It seems like something is broken either with the emulator action or the platform. Given there's nothing we can do about that in the short-term, I'm inclined to turn this emulator shard off again in CI.
